on:
  push:

env:
  ENVIRONMENT: prod

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variable
        run: echo "App is running in ${{ env.ENVIRONMENT }}"

      - name: Use secure API key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "Using API key:$API_KEY"
